### ISSUE TITLE
我想问下 00 -22 全都是必看的吗？

### ISSUE THREAD

**Issue by pdog18** [smyhvae/Web#1]
像 05-jQuery 也是要用到的吗？能否跳过呢

**Comment by smyhvae** [comment]
基本都是必看的。具体可以看我的这篇文章：
2018年Web前端入门的自学路线：http://www.cnblogs.com/smyhvae/p/8776837.html

另外，jQuery可能有点过时，但jQuery是前端基本功，是一定要掌握的。

**Comment by pdog18** [comment]
感谢回复，今天在公众号看到关于您的推送，我一样也是android -> web ，您的很多看法我都非常认可，以后向您多多学习了。
