### ISSUE TITLE
关于this例子的问题

### ISSUE THREAD

**Issue by zhang1pr** [smyhvae/Web#10]
Web/03-JavaScript进阶/this.md，{ 如果想打印每个div的id，应该这样写：console.log(this.id); }。我依照这一句话，把例子中的console.log(id)改为console.log(this.id)，但是输出还是undefined。不知是不是我理解错了。

链接：https://jsfiddle.net/fuckbr7y/

**Comment by zhang1pr** [comment]
Web/04-前端基本功：CSS和DOM练习/06-DOM操作练习：通过style对象设置样式.md，{20180129_1520.gif}，{20180129_1525.gif}，{20180204_1425.png}，三张图片无法显示。

**Comment by smyhvae** [comment]
this的例子，我这边打印是正常的，不是undefined，你可以把我的例子多试试。

gif图片的问题，已修复。谢谢提建议～
