### ISSUE TITLE
内容问题

### ISSUE THREAD

**Issue by Caibiy** [smyhvae/Web#12]
03-JavaScript基础/07-对象的创建、构造函数和原型
类和对象
为什么会有Java代码啊？ 
self.xxxx

**Comment by hufeicom** [comment]
不太理解原作者的初衷，也许是为了通过Java这种典型的面向对象语言说明JavaScript在定义一个类时的方式是by Class，而不是by Function。 所以会用Java代码来辅助说明作者的观点“函数并没有创建对象的能力，类才有。”。 在JavaScript中并没有严格意义上的Class和Function的区别，直接调用就可以看做function； 通过new关键字调用，就可以认为当成Class使用。通过阅读上下文也可以看出。

JavaScript并不是典型意义上的面向对象语言，它的对象简单来说就是一堆 **无序的键值对**。

**Comment by smyhvae** [comment]
@Caibiy  这不是Java代码，这是JavaScript的新特性。
